application: sylvan-shuttle-770
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /test
  script: test-task-php.php
  
- url: /.*
  script: signin.php

